channels:
- conda-forge
dependencies:
- python=3.11
- astropy=7.0.2
- bilby=2.2.2.1
- corner=2.2.3
- gwosc=0.7.1
- gwpy=3.0.11
- h5py=3.13.0
- ipykernel=7.0.1
- ipython=9.6.0
- lalsuite=7.25
- ligo.skymap=2.3.0
- numpy=1.24.4
- matplotlib-base=3.10.7
- matplotlib-inline=0.2.1
- pycbc=2.8.1
- scipy=1.13.1
name: igwn-py311
